name: Deploy Shiny app to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2

      # Install pak and shinylive from GitHub, then export
      - name: Install shinylive and export
        run: |
          R -e 'install.packages("pak", repos="https://cloud.r-project.org"); 
                pak::pak("posit-dev/r-shinylive"); 
                library(shinylive); 
                shinylive::export(".", "site")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
