name: Deploy Shiny app to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup R
      - uses: r-lib/actions/setup-r@v2

      # Install shinylive package
      - name: Install shinylive
        run: R -e 'install.packages("shinylive", repos="https://cloud.r-project.org")'

      # Export app to static site
      - name: Export Shiny app
        run: R -e 'library(shinylive); shinylive::export(".", "site")'

      # Push to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
